name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build for multiple platforms
        run: |
          mkdir -p dist

          # Build for Linux
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/tmrw-fix-linux-amd64
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o dist/tmrw-fix-linux-arm64

          # Build for macOS
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o dist/tmrw-fix-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o dist/tmrw-fix-darwin-arm64

          # Build for Windows
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o dist/tmrw-fix-windows-amd64.exe
          GOOS=windows GOARCH=arm64 go build -ldflags="-s -w" -o dist/tmrw-fix-windows-arm64.exe

          # Make binaries executable
          chmod +x dist/*

          # Create tar.gz archives
          cd dist
          tar czf tmrw-fix-linux-amd64.tar.gz tmrw-fix-linux-amd64
          tar czf tmrw-fix-linux-arm64.tar.gz tmrw-fix-linux-arm64
          tar czf tmrw-fix-darwin-amd64.tar.gz tmrw-fix-darwin-amd64
          tar czf tmrw-fix-darwin-arm64.tar.gz tmrw-fix-darwin-arm64
          tar czf tmrw-fix-windows-amd64.tar.gz tmrw-fix-windows-amd64.exe
          tar czf tmrw-fix-windows-arm64.tar.gz tmrw-fix-windows-arm64.exe

          # Clean up unarchived binaries
          rm tmrw-fix-*-*[!.tar.gz]

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/tmrw-fix-linux-amd64.tar.gz
            dist/tmrw-fix-linux-arm64.tar.gz
            dist/tmrw-fix-darwin-amd64.tar.gz
            dist/tmrw-fix-darwin-arm64.tar.gz
            dist/tmrw-fix-windows-amd64.tar.gz
            dist/tmrw-fix-windows-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
